### ISSUE TITLE
Cannot install gem: undefined reference to `__strcat_chk', undefined reference to `__chk_fail'

### ISSUE THREAD

**Issue by starrychloe** [Shopify/bootsnap#321]
Cannot install gem when running `bundle`. 

```
Fetching bootsnap 1.4.8
Installing bootsnap 1.4.8 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/ruby24/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.8/ext/bootsnap
C:/ruby24/bin/ruby.exe -r ./siteconf20201016-16408-4z4t6b.rb extconf.rb
creating Makefile

current directory:
C:/ruby24/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.8/ext/bootsnap
make "DESTDIR=" clean

current directory:
C:/ruby24/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.8/ext/bootsnap
make "DESTDIR="
generating bootsnap-x64-mingw32.def
compiling bootsnap.c
In file included from C:/ruby24/include/ruby-2.4.0/ruby.h:33,
                 from bootsnap.c:15:
C:/ruby24/include/ruby-2.4.0/ruby/ruby.h:631:1: warning: 'const' attribute on
function returning 'void' [-Wattributes]
  631 | CONSTFUNC(void rb_secure_update(VALUE));
      | ^~~~~~~~~
In file included from C:/ruby24/include/ruby-2.4.0/ruby/ruby.h:2008,
                 from C:/ruby24/include/ruby-2.4.0/ruby.h:33,
                 from bootsnap.c:15:
C:/ruby24/include/ruby-2.4.0/ruby/intern.h:257:1: warning: 'const' attribute on
function returning 'void' [-Wattributes]
  257 | CONSTFUNC(void rb_error_untrusted(VALUE));
      | ^~~~~~~~~
C:/ruby24/include/ruby-2.4.0/ruby/intern.h:259:1: warning: 'const' attribute on
function returning 'void' [-Wattributes]
  259 | CONSTFUNC(void rb_check_trusted(VALUE));
      | ^~~~~~~~~
linking shared-object bootsnap/bootsnap.so
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe:
bootsnap.o:bootsnap.c:(.text+0x564): undefined reference to `__strcat_chk'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe:
bootsnap.o:bootsnap.c:(.text+0xa1f): undefined reference to `__chk_fail'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:259: bootsnap.so] Error 1

make failed, exit code 2

Gem files will remain installed in
C:/ruby24/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.8 for inspection.
Results logged to
C:/ruby24/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/bootsnap-1.4.8/gem_make.out

An error occurred while installing bootsnap (1.4.8), and Bundler cannot
continue.
Make sure that `gem install bootsnap -v '1.4.8' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  bootsnap
```

Windows 8.1

```
>ridk version
---
ruby:
  path: C:/ruby24
  version: 2.4.3
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.3-1
  git_commit: 36aac73
msys2:
  path: C:\msys64
cc: x86_64-w64-mingw32-gcc (Rev4, Built by MSYS2 project) 10.2.0
sh: GNU bash, version 4.4.23(2)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.3.9600]
```
